In [1]:
# NIM/Nama : 16621282/Aura Maharani
# Tanggal : 1 Desember 2021
# Deskripsi : Program Analaisis Data

In [10]:
import pandas as pd

In [2]:
df = pd.read_csv("./downloads/H05.csv")

In [3]:
df

                                nama fakultas  nilai_mat  nilai_kim  nilai_fis
0               Farhan Fathur Rahman    FMIPA      57.21      34.14      38.93
1                     Steven Margono    FMIPA      67.43      51.50      57.20
2                       Ryan Sentosa    SAPPK      90.62      37.38      40.73
3               Muhajah Babny Muslim    FMIPA      72.31      38.80      44.79
4                   Alvin Natawiguna     FTSL      65.45      57.67      56.39
5                      Sasti Safitri     FTSL      60.58      41.91      51.55
6                Dani Yulianto Putra     FTSL      51.67      35.05      48.69
7     Nabila Febitsukarizky Bunyamin     FTTM      71.66      67.61      69.75
8                Ratna Siti Khodijah      FTI      73.06      59.16      59.48
9                       Gita Partiwi     FTSL      69.57      38.84      48.17
10             M Dharin Detama Patra     FITB      64.76      56.89      59.13
11                 Subhan Alimul Haq     FTTM      68.29      55.18      69.91
12                   Annisa Anindita      FTI      68.17      55.99      57.20
13                Devi Tiarani Putri      FTI      81.46      46.96      58.87
14        Nyoman Triani Herlina Dewi    SAPPK      79.33      37.99      43.00
15                     Putri Humaira      FTI      68.10      60.00      53.78
16             Fadhel Pramono Gartam      FTI      74.46      28.66      51.60
17                     Diana Octavia    FMIPA      84.23      31.62      36.46
18                Naufan Nurrosyid P     STEI      69.94      58.57      70.57
19                             Aaron    SAPPK      51.49      38.07      44.56
20                        Abdul Azis    FMIPA      90.14      31.05      49.40
21             Fatima Zahra Firdausi     FTMD      69.20      35.08      40.17
22                Iga Andita Lestari    SITHS      54.65      32.81      39.29
23         Muhammad Isyraqi El Hakim      FTI      74.28      51.67      56.67
24                    Yodi Pramudito     STEI      73.93      54.64      53.28
25                  Tiar Aji Saputra     FTTM      68.25      42.06      47.04
26                Diar Luthfi Hawari     STEI      73.06      12.98      30.11
27         Muhammad Naufal Farhandio     FITB      79.25      33.25      41.24
28         R B Emil Trisatya Nuriman      FTI      59.88      11.87      22.79
29                   Gilang Pangestu     STEI      75.10      44.97      53.38
...                              ...      ...        ...        ...        ...
5105              Made Lana Mahendra     FTTM      51.56      27.95      41.18
5106             Raymond Tanumiharja    SITHR      58.39      43.30      42.11
5107            Araaf Dinullah Recta     FITB      53.97      33.47      29.78
5108            Ananda Fitri Pratiwi    SITHR      76.30      54.78      63.44
5109                     Kevin Tigor     FTSL      84.47      56.13      54.72
5110              Mirza Dian Rifaldi    SITHR      62.51      59.61      72.85
5111         Amanda Farica Ajiwibowo     FTSL      69.09      37.54      43.34
5112                          Haikal     FTMD      55.16      46.77      58.86
5113                    Eko Widianto     FTSL      81.46      44.62      40.96
5114               Maratush Sholihah      FTI      53.56      47.87      54.07
5115        Mesa Gustya Siti Ulfiana      FTI      73.58      65.89      72.24
5116                   Deni Setiawan     STEI      76.78      68.54      82.87
5117            Ridho Muhammad Akbar    SITHR      81.78      35.50      41.94
5118                        Ray Ozma    SITHR      63.22      42.40      51.72
5119                  Kerry Addelina     FITB      57.52      50.63      47.25
5120           Muhammad Yusuf Afandi     FTSL      50.80      61.73      68.62
5121                   Harits Fathin     STEI      73.59      38.82      43.89
5122               Dharmawan Raharjo     STEI      42.16      42.15      52.73
5123             Siti Vivi Octaviany    FMIPA      72.85      64.49      69.56
5124        Astrid Felicia Rumintjap     FITB      50.43      45.27      60.43
5125              Prama Aditya Putra      FTI      82.75      28.87      44.88
5126        Seshana Junisa Aviananda     FTTM      81.11      34.82      24.48
5127            Dhimas Bayu Anindito     FITB      66.43      55.00      65.18
5128               Annisa Rachmanita     FTSL      63.11      51.61      55.12
5129               Sanchia Arindhita    SITHR      58.59      35.62      50.99
5130                     Khoirrashif    SITHR      66.14      46.82      56.74
5131            Jefri Hendri Adriano     FTSL      53.68      34.74      33.76
5132                     Iki Hidayat     FITB      69.63      35.04      37.65
5133        Muhammad Nashir Sitompul      FTI      79.69      39.06      50.17
5134           Billy Richardo Sagala     STEI      68.68      51.23      66.18

[5135 rows x 5 columns]

In [12]:
df_jumlah = len(df)
print("Banyaknya data adalah",df_jumlah)

Banyaknya data adalah 5135

In [6]:
print("10 data pertama adalah",df.head(10))

10 data pertama adalah                              nama fakultas  nilai_mat  nilai_kim  nilai_fis
0            Farhan Fathur Rahman    FMIPA      57.21      34.14      38.93
1                  Steven Margono    FMIPA      67.43      51.50      57.20
2                    Ryan Sentosa    SAPPK      90.62      37.38      40.73
3            Muhajah Babny Muslim    FMIPA      72.31      38.80      44.79
4                Alvin Natawiguna     FTSL      65.45      57.67      56.39
5                   Sasti Safitri     FTSL      60.58      41.91      51.55
6             Dani Yulianto Putra     FTSL      51.67      35.05      48.69
7  Nabila Febitsukarizky Bunyamin     FTTM      71.66      67.61      69.75
8             Ratna Siti Khodijah      FTI      73.06      59.16      59.48
9                    Gita Partiwi     FTSL      69.57      38.84      48.17

In [7]:
print("Data ke-50 sampai ke-10 adalah",df.iloc[50:61])

Data ke-50 sampai ke-10 adalah                         nama fakultas  nilai_mat  nilai_kim  nilai_fis
50      Arief Syakur Sutedjo     FTTM      84.40      61.21      73.91
51         Fayi Raihan Saleh    FMIPA      60.62      32.57      42.34
52          Erna Kristiawati      FTI      67.48      46.78      52.30
53                    Albert    SAPPK      70.27      50.10      54.01
54  M Jazztyan Indra Pradana     STEI      53.40      43.06      60.30
55      Moch Ginanjar Busiri    FMIPA      74.29      38.44      49.15
56              Aisya Tamara     FITB      71.49      35.86      37.41
57        Tyas Arum Widayati    SAPPK      68.57      37.02      53.25
58                Arif Saleh      FTI     100.00      59.79      55.33
59     Windy Diwita Nisaekti      FTI      67.15      57.72      54.24
60             Alif Aviano S     STEI      54.11      58.01      73.17

In [13]:
jumlah = df['fakultas'].value_counts()
print("Banyak mahasiswa tiap fakultas adalah",jumlah)

Banyak mahasiswa tiap fakultas adalah FTI      834
STEI     777
FTSL     660
FMIPA    627
FTTM     579
FTMD     480
FITB     403
SAPPK    315
SITHR    282
SITHS    178
Name: fakultas, dtype: int64

In [11]:
print("Nilai korelasi antara nilai fisika dan kimia adalah",df["nilai_kim"].corr(df["nilai_fis"]),"karena nilai korelasi mendekati satu, maka nilai fisika dan kimia berbanding lurus")

Nilai korelasi antara nilai fisika dan kimia adalah 0.798818742388 karena nilai korelasi mendekati satu, maka nilai fisika dan kimia berbanding lurus